title: SMAC+
author: MingyuKim
email: callingu@kaist.ac.kr
description: > # this means to ignore newlines until "show_exerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: SMAC+
  tagline: |
    Multi-Agent Challenges
    for Multi-Stage Tasks
  date_format: "%b %-d, %Y"
  sitemap: false # set to true to generate sitemap.xml content
  search: false # set to true to enable searchbar
  dark_mode: false # set to true to add dark mode toggle
  portfolio_image: "assets/smac_plus_image_2.png" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "en" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  condensed_mobile:
    - home
    # - page
    # - post
  # generate social links in footer
  social_links:
    # twitter: samarsault
    # googlescholar: nrZYdwQAAAAJ&hl=ko
    # linkedIn: in/mingyu-kim-0380a2125
    github:  osilab-kaist/smac_plus
    arxiv: 2207.02007
    #dribbble: jekyll
    #flickr:   jekyll
    #instagram: jekyll
    #pinterest: jekyll
    #youtube: jekyll
    #facebook: jekyll
    #soundcloud: jekyll
    #telegram: jekyll
    #gitlab: jekyll
    email: callingu@kaist.ac.kr

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: plainwhite
remote_theme: samarsault/plainwhite-jekyll

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
